services:
  - type: web
    name: quantum-fpm
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
